services:
  - type: web
    name: bakershub-app
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .

    startCommand: >
      php artisan key:generate --force &&
      chmod -R 775 storage bootstrap/cache &&
      chown -R www-data:www-data storage bootstrap/cache &&
      apache2-foreground

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: true # 🔥 TEMP (see real error)

      - key: APP_KEY
        value: base64:IaPOxVZQWjK3EY3fzOn6kWfdy72bREOJZaPCi+5Fctk=

      - key: APP_URL
        value: https://bakershub-full-stack-e-commerce-platform.onrender.com

      - key: LOG_CHANNEL
        value: errorlog

      # DB CONFIG
      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        value: bakershub-db

      - key: DB_PORT
        value: 3306

      - key: DB_DATABASE
        value: bakershub

      - key: DB_USERNAME
        value: bakershub

      - key: DB_PASSWORD
        value: ""

      # 🔥 TEMP SAFE SETTINGS (avoid Redis crash)
      - key: CACHE_DRIVER
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

    disk:
      name: bakershub-storage
      mountPath: /var/www/html/storage
      sizeGB: 1

  # MySQL
  - type: pserv
    name: bakershub-db
    env: mysql
    plan: starter

    envVars:
      - key: MYSQL_DATABASE
        value: bakershub

      - key: MYSQL_USER
        value: bakershub_user

      - key: MYSQL_PASSWORD
        generateValue: true

      - key: MYSQL_ROOT_PASSWORD
        generateValue: true

    disk:
      name: bakershub-db-disk
      mountPath: /var/lib/mysql
      sizeGB: 10
